/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stmpc1
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPPelajar = new javax.swing.JButton();
        btnPaparMaklumat = new javax.swing.JButton();
        btnKemaskiniMaklumat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KOLEJ KOMUNITI : MENU");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM PERMOHONAN PENGAJIAN KOLEJ");

        btnPPelajar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPPelajar.setText("PENDAFTARAN PELAJAR");
        btnPPelajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPelajarActionPerformed(evt);
            }
        });

        btnPaparMaklumat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPaparMaklumat.setText("PAPAR MAKLUMAT PELAJAR");
        btnPaparMaklumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaparMaklumatActionPerformed(evt);
            }
        });

        btnKemaskiniMaklumat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKemaskiniMaklumat.setText("KEMASKINI MAKLUMAT PELAJAR");
        btnKemaskiniMaklumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKemaskiniMaklumatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKemaskiniMaklumat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaparMaklumat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPPelajar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(btnPPelajar)
                .addGap(18, 18, 18)
                .addComponent(btnPaparMaklumat)
                .addGap(18, 18, 18)
                .addComponent(btnKemaskiniMaklumat)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPPelajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPelajarActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFPendaftaran form = new JFPendaftaran();
                form.setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnPPelajarActionPerformed

    private void btnPaparMaklumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaparMaklumatActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFMaklumat form = new JFMaklumat();
                form.setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnPaparMaklumatActionPerformed

    private void btnKemaskiniMaklumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKemaskiniMaklumatActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFKemaskini form = new JFKemaskini();
                form.setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnKemaskiniMaklumatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKemaskiniMaklumat;
    private javax.swing.JButton btnPPelajar;
    private javax.swing.JButton btnPaparMaklumat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
